name: Deployment

on:
  push:
    branches: [main]

jobs:
  build:
    name: 'Rebuild backend'
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: rebuild backend
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.CLOUD_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            node --version
            pwd
            cd ~/image-grader
            git fetch origin
            git checkout main
            git pull
            pm2 stop backend && pm2 reset backend
            yarn
            yarn build
            pm2 start backend
